# Generated by Django 4.2.2 on 2023-07-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("nickname", models.CharField(max_length=50)),
                ("comment", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
